
services:
  sim1:
    # First simulator container using f1tenth_gym_ros image
    image: f1tenth_gym_ros
    build: ./
    volumes:
      - .:/sim_ws/src/f1tenth_gym_ros
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    environment:
      # Display settings for X11 forwarding through NoVNC
      - DISPLAY=novnc1:0.0
      - QT_X11_NO_MITSHM=1
      - XAUTHORITY=/tmp/.Xauthority
      # ROS2 configuration for cross-container communication
      - ROS_DOMAIN_ID=0
      - ROS_NAMESPACE=sim1
    networks:
      - x11
      - ros_net
    stdin_open: true
    tty: true
    cap_add:
      - SYS_ADMIN
    security_opt:
      - seccomp:unconfined

  novnc1:
    # NoVNC container for the first simulator
    image: theasp/novnc:latest
    environment:
      - DISPLAY_WIDTH=1728
      - DISPLAY_HEIGHT=972
      - VNC_QUALITY=80
      - VNC_COMPRESSION=9
    ports:
      - "8080:8080"
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    networks:
      - x11

networks:
  x11:
  ros_net:
    # External network flag allows sharing between compose files
    external: true
    name: ros_net